version: "3.8"

services:
  api:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/tododb
      - PORT=5001

  mongo:
    image: mongo
    ports:
      - "27017:27017"
